### ISSUE TITLE
Graph: Time To Complete: Reassign colors

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#279]
In most (not all) cultures, green means good and red means bad. Traffic lights use green for go, yellow/orange for caution, and red for bad. Both response time graphs should follow this progression from green = best to red = worst.

It would also be nice to display on the target response time somewhere on the graph, or with the graph. These targets are set in Admin | Settings.

![image](https://cloud.githubusercontent.com/assets/329768/20104493/3030ba92-a59c-11e6-9ed6-7bd0b2f4354d.png)

**Comment by scloo** [comment]
Done

**Comment by gmcressman** [comment]
The colors still appear to me to be reversed, with "good" (less time) being red. So, for example, if the Notification target time is set to 24 hours, then notification:

< 24 hours should be green, 
<24-48 (target +24) should be yellow, 
48-72 (target + 48) should be orange, and 
72+ (>(Target + 48)) should be red.

In looking at this, I also realized that our wording is inconsistent, and that the graphs, and perhaps other parts of the app, are not using the Admin | Settings. In Admin | System Settings, there are two Response settings: 

Notification
Follow-up

In the graphs, we have two:

Time to Complete (set to 72 hours on the dev site)
Time to Notify (set to 48 hours on the dev site)

We need to make some changes so that our wording is consistent. In Issue #193 I go into detail about why we need 3 rather than just 2 timing targets. Reviewing #193, I suspect that the following might work:

Notification
Follow-up
Focus Investigation

The two graphs that we have now would then become:

Time to Notify
Time to Follow-up

And at some later point we would add "Time to Focus Investigation." As I recall, Mike explained to me that this query is possible in the current system.

@mikeymckay - you may have some insights on this, but we should also probably consult ZAMEP or Jeremiah.

It does not appear that the two graphs use the existing two response time target settings in Admin | Settings. There are also reports that should be using these settings.

**Comment by scloo** [comment]
Did you refresh your cache? On my side I see it in correct order. Anyhow I'll replace the blue with yellow.

**Comment by scloo** [comment]
I have made the various changes highlighted in this ticket. 
Regarding the last comment that the two graphs does not appear to use the existing two response time target settings, in the original ticket for these graphs, it appeared that Jeremiah's graphs was showing all the 4 values : 24hours to 72 hours. Hence these two graphs was showing that.  If we are to limit to the target settings in the Admin settings, then each of these 2 graphs should only have 1 color bar instead of 4. Is that what we want?

**Comment by gmcressman** [comment]
Nice work @scloo ! The colors are correct now. I"ll look at the way the original graphs handled the times before responding on that point.

**Comment by gmcressman** [comment]
Ok @scloo - here is what I see in Jeremiah's original time to notify (time from diagnosis to case notification) graph for the time intervals:

Within 24 hrs _(this is the target)_
25 to 72 hrs _(target+1 to target+48)_
Over 72 hrs _(>target+48)_
Not followed up (grey color)

So the bars can set up by just using fixed offsets from the target, which is set in Admin | Settings. The labeling in the legend must, of course, be dynamic to make this work..

I notice that we don't have that last category, which is very important. That is "Loss to follow-up." Does that exist in the view?

And for the time from notification to complete follow-up.

Within 48 hrs _(this is the target)_
3 to 7 days _(target+1 to target+120)_
More than 1 week _(>target+120)_
Not followed up (grey color)

So, for this graph also the bars can set up by just using fixed offsets from the target, which is set in Admin | Settings. Again, the labeling in the legend must be dynamic to make this work. For simplicity, just label everything in hours.

Does that makes sense to you?

**Comment by gmcressman** [comment]
The colors are correct, but the graphs still need to work off the settings, and we need to try to match Jeremiah's intervals and colors above. Do we have "Lost to Follow-up" in this view?

**Comment by gmcressman** [comment]
@scloo - Please see the above comments on this issue.

**Comment by gmcressman** [comment]
Needs "Not followed up" as top series, in grey. Need to find a good way to make series intervals soft. Moving back to In Progress at top.

**Comment by gmcressman** [comment]
Closing. Time to Follow-up Legend and colors still not correct. Will open new issue for this.
